artifact_location: file:///C:/Users/asitk/Desktop/Flower_detector-main/runs/mlflow/400211434144877772
creation_time: 1760816191101
experiment_id: '400211434144877772'
last_update_time: 1760816191101
lifecycle_stage: active
name: /Shared/Ultralytics
